build:
  image: buvoli/clearlinux-sc:v0.2.0
environment:
  JULIA_DEPOT_PATH: "/opt/shared/julia-depot" # used in place of ~/.julia
  DYNAMIC_USER: "user"
environment-dynamic:
  DYNAMIC_UID: "$(id -u)"
  DYNAMIC_GID: "$(id -g)"
mounts:
  - type: "bind"
    hostPath: "config/jupyter"
    containerPath: "/home/user/.jupyter"
  - type: "bind"
    hostPath: "config/theia"
    containerPath: "/home/user/.theia"
  - type: "bind"
    hostPath: "config/cjr"
    containerPath: "/home/user/.config/cjr"
files:
  containerRoot: "/home/user"
flags:
  userns: keep-id
  docker-chown-file-volume: "host-user"
  cmd-args: join